commit_message: '[skip ci] Update translations (%language%) %original_file_name%'
append_commit_message: false
pull_request_title: 'i18n: update translations'
pull_request_labels:
  - i18n
files:
  - source: src/**/*.md
    translation: src/%locale%/**/%original_file_name%.md
  - source: .vitepress/locales/zh-CN.json
    translation: .vitepress/locales/%locale%.json
