name: DEPLOYMENT

on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version:
          - 18

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      # 构建
      - name: Build
        run: pnpm build

      # 部署
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          # 删除服务器上目录里所有文件
          # ARGS: '-avz --delete'
          # 项目 build 后静态文件位置
          SOURCE: './dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
