name: Compressed Size

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'build'
          clean-script: 'rm -rf dist/'
          pattern: './build/**/*.{js,css,html,json}'
          exclude: '{./build-output/manifest.json,**/*.map,**/node_modules/**}'
